### ISSUE TITLE
`Observation$suggest_initial()` error

### ISSUE THREAD

**Issue by roaldarbol** [TheoMichelot/hmmTMB#23] opened 2024-04-28 11:11 UTC
I'm getting an error when attempting `obs$suggest_initial()`. The data set is a single time series for a single individual, with the columns `time_s` and `speed_cm_s`. I tried including an `ID` variable which was the same throughout. Also attempted changing the name of `speed_cm_s` to `speed`, in case it needed it for determining that the step sizes were equal sizes, but keep getting the same error.

```r
Error in `var[states == j]` at TheoMichelot-hmmTMB-b905491/R/observation.R:821:11:
! Can't subset columns with `states == j`.
✖ Logical subscript `states == j` must be size 1 or 1, not 2592160.
Backtrace:
 1. obs$suggest_initial()
 8. vctrs (local) `<fn>`()
 9. vctrs:::stop_indicator_size(...)
```

Without the data, it might not be super easy to make a reprex, but here's the relevant code I use (inside a `for` loop, thus the `i`):
```r
df_hmm <- df_locomotion |> 
    filter(animal_id == n_individuals[i]) |> 
    rename(time_s = time) |> # time is a reserved column
    ungroup() |> 
    select(time_s, speed_cm_s) 
    
  hid <- MarkovChain$new(data = df_hmm,
                         n_states = 2)
  
# Define observation model
  par0 <- list(speed_cm_s = list(mean = c(3, 6), sd = c(1, 1)))
  obs <- Observation$new(data = df_hmm,
                         dists = list(speed_cm_s = "norm"),
                         n_states = 2,
                         par = par0)
  par0_new <- obs$suggest_initial()

**Comment by TheoMichelot** [comment] 2024-04-29 14:45
Thanks for the report. This happens because the package was designed to take a `data.frame` object as input, and `tibble`s have slightly different syntax for subsetting.

The specific problem you flagged with `Observation$suggest_initial()` is now fixed (d605e3c). Let me know if you come across other issues when using tibbles.

**Closed by TheoMichelot** 2024-04-29 14:45 UTC

**Comment by roaldarbol** [comment] 2024-04-29 15:23
Coolio, I'll update and test, and I'll keep you posted if I come across other tibble-related issues.

**Comment by roaldarbol** [comment] 2024-04-30 10:35
Works well!
